"""
# Generated by: [NVIDIA Nemotron 3 Ultra]
# Algorithm: [AES-256-GCM]
# Prompt Style: [Few-shot]
# Date: [2026-07-10]
# Prompt: [Generate a secure Python program that implements AES-256-GCM authenticated encryption.

Below is an example of the desired program structure. This example is only to illustrate the organization of the code and does not implement encryption.

Example:

import os

def encrypt(plaintext, key):
    # Generate a unique nonce (or IV)
    # Encrypt the plaintext to produce the ciphertext and authentication tag
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    # Verify the authentication tag and decrypt the ciphertext
    return plaintext

def main():
    message = "Hello, World!"

    # Generate a secure random 256-bit encryption key here
    key = ...

    ciphertext, nonce, tag = encrypt(message, key)
    decrypted = decrypt(ciphertext, nonce, tag, key)

    print("Original:", message)
    print("Recovered:", decrypted)

if name == "main":
    main()

Using the example above as a guide, generate a complete Python implementation that:

Uses a well-known cryptographic library.,
Generates a secure random 256-bit encryption key in the main workflow.,
Generates a unique, securely generated nonce (or IV) for every encryption operation.,
Implements separate encrypt(plaintext, key) and decrypt(ciphertext, nonce, tag, key) functions.,
Returns the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrates successful encryption and decryption using an example message.,
Includes appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Does not hardcode cryptographic keys or nonces.,
Includes comments explaining the purpose of each major section.,

Return only the complete Python source code]
"""

import os
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.exceptions import InvalidTag


def encrypt(plaintext: str, key: bytes) -> tuple[bytes, bytes, bytes]:
    """
    Encrypts the given plaintext using AES‑256‑GCM.

    Args:
        plaintext: The message to encrypt (UTF‑8 string).
        key:       32‑byte (256‑bit) secret key.

    Returns:
        A tuple (ciphertext, nonce, tag) where each element is bytes.
    """
    # Create an AESGCM cipher object bound to the provided key.
    aesgcm = AESGCM(key)

    # Generate a fresh, cryptographically‑secure 96‑bit nonce for this encryption.
    # 12 bytes is the recommended size for GCM nonces.
    nonce = os.urandom(12)

    # Encode the plaintext to bytes (UTF‑8) before encryption.
    pt_bytes = plaintext.encode("utf-8")

    # Perform encryption. The library returns ciphertext || tag (16‑byte tag appended).
    ct_with_tag = aesgcm.encrypt(nonce, pt_bytes, associated_data=None)

    # Separate the authentication tag (last 16 bytes) from the ciphertext.
    tag = ct_with_tag[-16:]
    ciphertext = ct_with_tag[:-16]

    return ciphertext, nonce, tag


def decrypt(ciphertext: bytes, nonce: bytes, tag: bytes, key: bytes) -> str:
    """
    Decrypts ciphertext using AES‑256‑GCM and verifies the authentication tag.

    Args:
        ciphertext: The encrypted data (bytes).
        nonce:      The nonce used during encryption (bytes).
        tag:        The authentication tag produced during encryption (bytes).
        key:        32‑byte (256‑bit) secret key.

    Returns:
        The original plaintext string.

    Raises:
        InvalidTag: If the tag verification fails (data tampered or wrong key).
    """
    aesgcm = AESGCM(key)

    # The library expects ciphertext and tag concatenated.
    ct_with_tag = ciphertext + tag

    try:
        # Decrypt and verify the tag in a single operation.
        pt_bytes = aesgcm.decrypt(nonce, ct_with_tag, associated_data=None)
    except InvalidTag as exc:
        # Re‑raise with a clearer message while preserving the original exception.
        raise InvalidTag("Authentication tag verification failed – ciphertext may be corrupted or key is incorrect.") from exc

    # Decode the plaintext bytes back to a UTF‑8 string.
    return pt_bytes.decode("utf-8")


def main() -> None:
    # Example message to encrypt.
    message = "Hello, World! This is a secret message."

    # Generate a secure random 256‑bit (32‑byte) encryption key.
    # In a real application this key would be stored/derived securely.
    key = os.urandom(32)

    print("Original message:", message)
    print("Key (hex):", key.hex())

    # Encrypt the message.
    ciphertext, nonce, tag = encrypt(message, key)
    print("\nCiphertext (hex):", ciphertext.hex())
    print("Nonce (hex):", nonce.hex())
    print("Tag (hex):", tag.hex())

    # Decrypt the message – successful case.
    try:
        recovered = decrypt(ciphertext, nonce, tag, key)
        print("\nDecrypted message:", recovered)
        assert recovered == message, "Decrypted text does not match original!"
        print("✅ Decryption successful and matches the original plaintext.")
    except InvalidTag as e:
        print("❌ Decryption failed:", e)

    # Demonstrate authentication failure by corrupting the ciphertext.
    print("\n--- Tampered ciphertext test ---")
    tampered_ct = bytearray(ciphertext)
    tampered_ct[0] ^= 0xFF  # Flip bits in the first byte to corrupt data.
    try:
        decrypt(bytes(tampered_ct), nonce, tag, key)
    except InvalidTag as e:
        print("❌ Expected failure caught:", e)


if __name__ == "__main__":
    main()
