"""
# Generated by: [NVIDIA Nemotron 3 Ultra]
# Algorithm: [AES-256-GCM]
# Prompt Style: [Chain-of-Thought]
# Date: [2026-07-10]
# Prompt: [Generate a secure Python program that implements AES-256-GCM authenticated encryption.

Before generating the Python code, carefully reason through the design of the implementation by considering:

How to securely generate a random 256-bit encryption key.,
How to securely generate a unique nonce (or IV) for every encryption operation.,
How AES-256-GCM provides both confidentiality and authentication.,
How the authentication tag should be generated, returned, and verified during decryption.,
How to structure the program into separate encrypt() and decrypt() functions.,
How to properly handle authentication/tag verification failures using exception handling.,
How to avoid common cryptographic implementation mistakes, such as hardcoded keys, nonce reuse, and insecure randomness.,

After completing your reasoning, generate a complete Python implementation that:

Uses Python.,
Uses a well-known cryptographic library.,
Implements AES-256-GCM authenticated encryption.,
Generates a secure random 256-bit encryption key.,
Generates a unique, securely generated nonce (or IV) for every encryption operation.,
Implements separate encrypt(plaintext, key) and decrypt(ciphertext, nonce, tag, key) functions.,
Returns the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrates successful encryption and decryption using an example message.,
Includes appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Does not hardcode cryptographic keys or nonces.,
Includes comments explaining the purpose of each major section.,

Perform your reasoning steps internally or wrap them in comments, and ensure the final output provides the complete, valid Python source code.
"""

"""
AES‑256‑GCM authenticated encryption example.

Design rationale (embedded as comments for clarity):
---------------------------------------------------
1. **Key generation** – Use `os.urandom(32)` to obtain 256 bits of cryptographically‑secure
   randomness.  The key is never hard‑coded and should be stored/derived securely in a real
   application (e.g., via a KDF or HSM).

2. **Nonce/IV generation** – GCM requires a unique nonce for every encryption under the same
   key.  A 96‑bit (12‑byte) nonce generated with `os.urandom(12)` satisfies NIST recommendations
   and makes the probability of a repeat negligible.

3. **AES‑256‑GCM properties** – The mode provides:
   * *Confidentiality* via AES‑CTR encryption.
   * *Integrity & authenticity* via a 128‑bit authentication tag (GHASH).
   The tag is bound to the ciphertext, associated data (none here), and the nonce.

4. **Tag handling** – `cryptography.hazmat.primitives.ciphers.aead.AESGCM.encrypt`
   returns `ciphertext || tag`.  We split the last 16 bytes as the tag and return
   `(ciphertext, nonce, tag)` separately so the caller can store/transmit them independently.

5. **Function separation** – `encrypt(plaintext, key)` performs key‑binding, nonce creation,
   encryption, and tag extraction.  `decrypt(ciphertext, nonce, tag, key)` recombines
   ciphertext+tag, verifies the tag, and decrypts.  This mirrors typical API designs
   and keeps concerns isolated.

6. **Exception handling** – `AESGCM.decrypt` raises `cryptography.exceptions.InvalidTag`
   when verification fails (tampered data, wrong key, nonce reuse).  We catch this
   specific exception and re‑raise with a clear message, allowing callers to handle
   authentication failures explicitly.

7. **Avoiding common mistakes** – No hard‑coded secrets, fresh nonce per encryption,
   use of OS‑provided CSPRNG, and explicit tag verification.  Associated data is omitted
   for simplicity but can be added without changing the structure.
"""

import os
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.exceptions import InvalidTag


def encrypt(plaintext: str, key: bytes) -> tuple[bytes, bytes, bytes]:
    """
    Encrypt `plaintext` with AES‑256‑GCM.

    Args:
        plaintext: UTF‑8 string to protect.
        key:       32‑byte (256‑bit) secret key.

    Returns:
        (ciphertext, nonce, tag) – each as `bytes`.
    """
    # Bind the key to an AESGCM primitive.
    aesgcm = AESGCM(key)

    # Fresh, cryptographically‑secure 96‑bit nonce for this operation.
    nonce = os.urandom(12)

    # Convert the message to bytes (UTF‑8) before encryption.
    pt_bytes = plaintext.encode("utf-8")

    # Encrypt; library returns ciphertext concatenated with 16‑byte tag.
    ct_with_tag = aesgcm.encrypt(nonce, pt_bytes, associated_data=None)

    # Separate the authentication tag (last 16 bytes) from the ciphertext.
    tag = ct_with_tag[-16:]
    ciphertext = ct_with_tag[:-16]

    return ciphertext, nonce, tag


def decrypt(ciphertext: bytes, nonce: bytes, tag: bytes, key: bytes) -> str:
    """
    Decrypt and verify `ciphertext` using AES‑256‑GCM.

    Args:
        ciphertext: Encrypted data (bytes).
        nonce:      Nonce used during encryption (bytes).
        tag:        Authentication tag produced during encryption (bytes).
        key:        32‑byte (256‑bit) secret key.

    Returns:
        Original plaintext string.

    Raises:
        InvalidTag: If tag verification fails (data corrupted or key mismatch).
    """
    aesgcm = AESGCM(key)

    # The primitive expects ciphertext||tag as a single buffer.
    ct_with_tag = ciphertext + tag

    try:
        # Decrypt and verify the tag in one atomic step.
        pt_bytes = aesgcm.decrypt(nonce, ct_with_tag, associated_data=None)
    except InvalidTag as exc:
        # Provide a clearer diagnostic while preserving the original traceback.
        raise InvalidTag(
            "Authentication tag verification failed – ciphertext may be corrupted, "
            "the key is incorrect, or the nonce was reused."
        ) from exc

    # Decode the recovered plaintext bytes back to a string.
    return pt_bytes.decode("utf-8")


def main() -> None:
    # Example message.
    message = "Hello, World! This is a confidential message."

    # Generate a secure random 256‑bit key (32 bytes).  In production this would be
    # stored/derived via a KDF, HSM, or key‑management system.
    key = os.urandom(32)

    print("Original message:", message)
    print("Key (hex):", key.hex())

    # Encrypt.
    ciphertext, nonce, tag = encrypt(message, key)
    print("\nCiphertext (hex):", ciphertext.hex())
    print("Nonce (hex):", nonce.hex())
    print("Tag (hex):", tag.hex())

    # Successful decryption.
    try:
        recovered = decrypt(ciphertext, nonce, tag, key)
        print("\nDecrypted message:", recovered)
        assert recovered == message, "Decrypted text does not match original!"
        print("✅ Decryption successful and matches the original plaintext.")
    except InvalidTag as e:
        print("❌ Decryption failed:", e)

    # Demonstrate authentication failure by corrupting the ciphertext.
    print("\n--- Tampered ciphertext test ---")
    tampered_ct = bytearray(ciphertext)
    tampered_ct[0] ^= 0xFF  # Flip bits in the first byte.
    try:
        decrypt(bytes(tampered_ct), nonce, tag, key)
    except InvalidTag as e:
        print("❌ Expected failure caught:", e)


if __name__ == "__main__":
    main()
```]
"""

