"""
# Generated by: [NVIDIA Nemotron 3 Ultra]
# Algorithm: [ChaCha20-Poly1305]
# Prompt Style: [Zero-shot]
# Date: [2026-07-10]
# Prompt: [Requirements:
Use Python.,
Use a well-known cryptographic library,
Implement a modern, secure authenticated encryption algorithm (AEAD), ChaCha20-Poly1305.,
Generate a random 256-bit encryption key.,
Generate a unique, securely generated nonce (or IV) appropriate for every encryption operation.,
Create separate encrypt() and decrypt() functions.,
Accept plaintext as a string.,
Return the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrate the encryption and decryption process using an example message.,
Include appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Include comments explaining the purpose of each major section.,

Return only the complete Python source code.]
"""

# -*- coding: utf-8 -*-
"""
Authenticated Encryption with ChaCha20‑Poly1305 (AEAD)

This script demonstrates:
* Generation of a random 256‑bit key.
* Generation of a fresh, cryptographically‑secure nonce for each encryption.
* Separate encrypt() and decrypt() functions.
* Returning ciphertext, nonce, and authentication tag as distinct values.
* Proper exception handling for tag verification failures.
"""

import os
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.exceptions import InvalidTag


def generate_key() -> bytes:
    """
    Generate a random 256‑bit (32‑byte) key suitable for ChaCha20‑Poly1305.
    """
    return os.urandom(32)                     # 32 bytes = 256 bits


def generate_nonce() -> bytes:
    """
    Generate a fresh 96‑bit (12‑byte) nonce for ChaCha20‑Poly1305.
    The nonce must never be reused with the same key.
    """
    return os.urandom(12)                     # 12 bytes = 96 bits


def encrypt(key: bytes, plaintext: str, associated_data: bytes = b"") -> tuple[bytes, bytes, bytes]:
    """
    Encrypt ``plaintext`` using ChaCha20‑Poly1305.

    Parameters
    ----------
    key : bytes
        32‑byte encryption key.
    plaintext : str
        Message to encrypt (UTF‑8 encoded internally).
    associated_data : bytes, optional
        Additional authenticated data (AAD) that is not encrypted but is authenticated.

    Returns
    -------
    tuple(ciphertext, nonce, tag)
        * ciphertext : bytes – the encrypted payload (without the authentication tag).
        * nonce      : bytes – the 12‑byte nonce used for this encryption.
        * tag        : bytes – 16‑byte authentication tag.
    """
    # Create a new ChaCha20Poly1305 instance with the supplied key
    aead = ChaCha20Poly1305(key)

    # Generate a unique nonce for this encryption operation
    nonce = generate_nonce()

    # Encode the plaintext string to bytes (UTF‑8)
    pt_bytes = plaintext.encode("utf-8")

    # Encrypt – the library returns ciphertext || tag (tag is 16 bytes)
    ct_with_tag = aead.encrypt(nonce, pt_bytes, associated_data)

    # Split the returned bytes into ciphertext and tag
    tag = ct_with_tag[-16:]               # last 16 bytes = authentication tag
    ciphertext = ct_with_tag[:-16]        # everything before the tag

    return ciphertext, nonce, tag


def decrypt(key: bytes, ciphertext: bytes, nonce: bytes, tag: bytes,
            associated_data: bytes = b"") -> str:
    """
    Decrypt a ciphertext produced by ``encrypt`` and verify its authenticity.

    Parameters
    ----------
    key : bytes
        32‑byte encryption key (must match the one used for encryption).
    ciphertext : bytes
        Encrypted payload (without the tag).
    nonce : bytes
        12‑byte nonce used during encryption.
    tag : bytes
        16‑byte authentication tag.
    associated_data : bytes, optional
        The same AAD that was supplied during encryption.

    Returns
    -------
    str
        The original plaintext string.

    Raises
    ------
    cryptography.exceptions.InvalidTag
        If the tag verification fails (ciphertext tampered or wrong key/nonce).
    """
    # Re‑assemble ciphertext + tag as expected by the library
    ct_with_tag = ciphertext + tag

    aead = ChaCha20Poly1305(key)

    # Decrypt and verify – will raise InvalidTag on failure
    pt_bytes = aead.decrypt(nonce, ct_with_tag, associated_data)

    # Decode back to string
    return pt_bytes.decode("utf-8")


# -------------------------------------------------------------------------
# Demonstration
# -------------------------------------------------------------------------
if __name__ == "__main__":
    # 1️⃣ Generate a fresh key (in practice you would store this securely)
    key = generate_key()

    # 2️⃣ Example message
    message = "Confidential data: the answer is 42."

    # 3️⃣ Encrypt
    try:
        ct, nonce, tag = encrypt(key, message)
        print("Encryption succeeded.")
        print(f"Ciphertext (hex): {ct.hex()}")
        print(f"Nonce (hex)      : {nonce.hex()}")
        print(f"Tag (hex)        : {tag.hex()}")
    except Exception as e:
        print(f"Encryption failed: {e}")

    # 4️⃣ Decrypt – normal case
    try:
        recovered = decrypt(key, ct, nonce, tag)
        print("\nDecryption succeeded.")
        print(f"Recovered plaintext: {recovered}")
    except InvalidTag:
        print("\nDecryption failed: authentication tag verification error.")
    except Exception as e:
        print(f"\nDecryption failed with unexpected error: {e}")

    # 5️⃣ Decrypt – tampered ciphertext (demonstrates exception handling)
    tampered_ct = bytearray(ct)
    if tampered_ct:
        tampered_ct[0] ^= 0xFF                     # flip a bit
    try:
        decrypt(key, bytes(tampered_ct), nonce, tag)
    except InvalidTag:
        print("\nTampered ciphertext correctly rejected (InvalidTag).")
    except Exception as e:
        print(f"\nUnexpected error during tampered decryption: {e}")
