"""
AES‑GCM authenticated encryption example using the `cryptography` library.

Features demonstrated:
- Generation of a random 256‑bit (32‑byte) key.
- Generation of a fresh, cryptographically‑secure 96‑bit (12‑byte) nonce for each encryption.
- Separate `encrypt()` and `decrypt()` functions.
- `encrypt()` returns ciphertext, nonce, and authentication tag as distinct values.
- `decrypt()` verifies the tag and raises an exception on failure.
- Proper exception handling for tag verification errors.

# Generated by: [NVIDIA Nemotron 3 Ultra]
# Algorithm: [AES-256-GCM]
# Prompt Style: [Zero-shot]
# Date: [2026-07-10]
# Prompt: [Requirements:
Use Python.,
Use a well-known cryptographic library,
Implement a modern, secure authenticated encryption algorithm (AEAD), AES-GCM.,
Generate a random 256-bit encryption key.,
Generate a unique, securely generated nonce (or IV) appropriate for every encryption operation.,
Create separate encrypt() and decrypt() functions.,
Accept plaintext as a string.,
Return the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrate the encryption and decryption process using an example message.,
Include appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Include comments explaining the purpose of each major section.,

Return only the complete Python source code.]
"""

import os
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.exceptions import InvalidTag


def generate_key() -> bytes:
    """
    Generate a random 256‑bit (32‑byte) key suitable for AES‑GCM.
    """
    return os.urandom(32)          # 32 bytes = 256 bits


def generate_nonce() -> bytes:
    """
    Generate a fresh 96‑bit (12‑byte) nonce for AES‑GCM.
    The 96‑bit size is recommended by NIST for GCM.
    """
    return os.urandom(12)          # 12 bytes = 96 bits


def encrypt(key: bytes, plaintext: str) -> tuple[bytes, bytes, bytes]:
    """
    Encrypt `plaintext` using AES‑GCM with the provided `key`.

    Returns a tuple:
        (ciphertext, nonce, tag)

    - `ciphertext` : the encrypted data (bytes)
    - `nonce`      : the nonce used for this encryption (bytes)
    - `tag`        : the authentication tag (bytes)
    """
    # Create an AESGCM cipher object with the supplied key
    aesgcm = AESGCM(key)

    # Generate a unique nonce for this encryption operation
    nonce = generate_nonce()

    # Encode the plaintext string to bytes (UTF‑8)
    pt_bytes = plaintext.encode("utf-8")

    # Perform encryption; AESGCM.encrypt returns ciphertext || tag concatenated.
    # We ask for the tag separately by using `encrypt` and then slicing,
    # but the library returns the tag appended, so we split it.
    # The tag length for AES‑GCM is 16 bytes.
    ct_with_tag = aesgcm.encrypt(nonce, pt_bytes, associated_data=None)

    # Separate ciphertext and tag
    tag = ct_with_tag[-16:]          # last 16 bytes = authentication tag
    ciphertext = ct_with_tag[:-16]   # everything before the tag

    return ciphertext, nonce, tag


def decrypt(key: bytes, nonce: bytes, ciphertext: bytes, tag: bytes) -> str:
    """
    Decrypt `ciphertext` using AES‑GCM with the provided `key`, `nonce`, and `tag`.

    Returns the original plaintext string.

    Raises:
        InvalidTag: if the authentication tag does not verify (tampered data).
    """
    aesgcm = AESGCM(key)

    # Re‑assemble ciphertext and tag as expected by the library
    ct_with_tag = ciphertext + tag

    try:
        # Decrypt and verify the tag in one step
        pt_bytes = aesgcm.decrypt(nonce, ct_with_tag, associated_data=None)
    except InvalidTag as exc:
        # Re‑raise with a clearer message (optional)
        raise InvalidTag("Authentication tag verification failed – data may be corrupted or tampered.") from exc

    # Decode bytes back to string (UTF‑8)
    return pt_bytes.decode("utf-8")


# -------------------------------------------------------------------------
# Demonstration
# -------------------------------------------------------------------------
if __name__ == "__main__":
    # 1. Generate a random 256‑bit key (in practice, store this securely)
    key = generate_key()
    print(f"Key (hex): {key.hex()}")

    # 2. Example plaintext message
    message = "Hello, AES‑GCM! This is a confidential message."
    print(f"Original plaintext: {message}")

    # 3. Encrypt the message
    ciphertext, nonce, tag = encrypt(key, message)
    print(f"Ciphertext (hex): {ciphertext.hex()}")
    print(f"Nonce (hex):      {nonce.hex()}")
    print(f"Tag (hex):        {tag.hex()}")

    # 4. Decrypt the message (successful case)
    try:
        decrypted = decrypt(key, nonce, ciphertext, tag)
        print(f"Decrypted plaintext: {decrypted}")
        assert decrypted == message, "Decrypted text does not match original!"
        print("✅ Decryption successful and matches original plaintext.")
    except InvalidTag as e:
        print(f"❌ Decryption failed: {e}")

    # 5. Demonstrate authentication failure by corrupting the ciphertext
    corrupted_ct = bytearray(ciphertext)
    corrupted_ct[0] ^= 0xFF  # flip bits in the first byte
    print("\n--- Tampered ciphertext test ---")
    try:
        decrypt(key, nonce, bytes(corrupted_ct), tag)
    except InvalidTag as e:
        print(f"❌ Expected failure caught: {e}")
