"""
# Generated by: [NVIDIA Nemotron 3 Ultra]
# Algorithm: [ChaCha20-Poly1305]
# Prompt Style: [Few-shot]
# Date: [2026-07-10]
# Prompt: [Generate a secure Python program that implements ChaCha20-Poly1305 authenticated encryption.

Below is an example of the desired program structure. This example is only to illustrate the organization of the code and does not implement encryption.

Example:

import os

def encrypt(plaintext, key):
    # Generate a unique nonce
    # Encrypt the plaintext to produce the ciphertext and Poly1305 authentication tag
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    # Verify the Poly1305 authentication tag and decrypt the ciphertext
    return plaintext

def main():
    message = "Hello, World!"

    # Generate a secure random 256-bit encryption key here
    key = ...

    ciphertext, nonce, tag = encrypt(message, key)
    decrypted = decrypt(ciphertext, nonce, tag, key)

    print("Original:", message)
    print("Recovered:", decrypted)

if name == "main":
    main()

Using the example above as a guide, generate a complete Python implementation that:

Uses a well-known cryptographic library.,
Generates a secure random 256-bit encryption key in the main workflow.,
Generates a unique, securely generated nonce appropriate for ChaCha20-Poly1305 for every encryption operation.,
Implements separate encrypt(plaintext, key) and decrypt(ciphertext, nonce, tag, key) functions.,
Returns the ciphertext, nonce, and authentication tag as separate values from the encrypt() function.,
Demonstrates successful encryption and decryption using an example message.,
Includes appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Does not hardcode cryptographic keys or nonces.,
Includes comments explaining the purpose of each major section.,

Return only the complete Python source code.]
"""

import os
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.exceptions import InvalidTag


def encrypt(plaintext: str, key: bytes) -> tuple[bytes, bytes, bytes]:
    """
    Encrypt `plaintext` with ChaCha20‑Poly1305.

    Parameters
    ----------
    plaintext : str
        The message to encrypt (UTF‑8 encoded internally).
    key : bytes
        32‑byte (256‑bit) secret key.

    Returns
    -------
    tuple(ciphertext, nonce, tag)
        * ciphertext : bytes – encrypted data (without the authentication tag)
        * nonce      : bytes – 12‑byte nonce used for this operation
        * tag        : bytes – 16‑byte Poly1305 authentication tag
    """
    # Initialise the AEAD cipher with the provided key
    aead = ChaCha20Poly1305(key)

    # Generate a fresh, cryptographically‑secure 96‑bit nonce (12 bytes)
    nonce = os.urandom(12)

    # Convert the string to bytes (UTF‑8) before encryption
    pt_bytes = plaintext.encode("utf-8")

    # Encrypt – the library returns ciphertext || tag (tag is 16 bytes)
    ct_with_tag = aead.encrypt(nonce, pt_bytes, None)

    # Separate the authentication tag from the ciphertext
    tag = ct_with_tag[-16:]          # last 16 bytes = tag
    ciphertext = ct_with_tag[:-16]   # everything before the tag

    return ciphertext, nonce, tag


def decrypt(ciphertext: bytes, nonce: bytes, tag: bytes, key: bytes) -> str:
    """
    Decrypt and verify a ciphertext produced by `encrypt`.

    Parameters
    ----------
    ciphertext : bytes
        Encrypted payload (without the tag).
    nonce : bytes
        12‑byte nonce used during encryption.
    tag : bytes
        16‑byte authentication tag.
    key : bytes
        32‑byte secret key (must match the encryption key).

    Returns
    -------
    str
        The original plaintext.

    Raises
    ------
    InvalidTag
        If the tag verification fails (tampered data, wrong key/nonce, etc.).
    """
    # Re‑assemble ciphertext + tag as expected by the library
    ct_with_tag = ciphertext + tag

    aead = ChaCha20Poly1305(key)

    # Decrypt and verify authenticity; raises InvalidTag on failure
    pt_bytes = aead.decrypt(nonce, ct_with_tag, None)

    # Decode back to a string
    return pt_bytes.decode("utf-8")


def main() -> None:
    # Example message to protect
    message = "Hello, World!"

    # Generate a secure random 256‑bit (32‑byte) key
    key = os.urandom(32)

    # ----- Encryption -----
    try:
        ciphertext, nonce, tag = encrypt(message, key)
        print("Encryption succeeded.")
        print(f"Ciphertext (hex): {ciphertext.hex()}")
        print(f"Nonce (hex)      : {nonce.hex()}")
        print(f"Tag (hex)        : {tag.hex()}")
    except Exception as exc:
        print(f"Encryption failed: {exc}")
        return

    # ----- Decryption (normal case) -----
    try:
        recovered = decrypt(ciphertext, nonce, tag, key)
        print("\nDecryption succeeded.")
        print(f"Original : {message}")
        print(f"Recovered: {recovered}")
    except InvalidTag:
        print("\nDecryption failed: authentication tag verification error.")
        return
    except Exception as exc:
        print(f"\nDecryption failed with unexpected error: {exc}")
        return

    # ----- Demonstrate tag verification failure on tampered data -----
    # Flip a bit in the ciphertext to simulate corruption / tampering
    tampered_ct = bytearray(ciphertext)
    if tampered_ct:
        tampered_ct[0] ^= 0xFF

    try:
        decrypt(bytes(tampered_ct), nonce, tag, key)
    except InvalidTag:
        print("\nTampered ciphertext correctly rejected (InvalidTag).")
    except Exception as exc:
        print(f"\nUnexpected error during tampered decryption: {exc}")


if __name__ == "__main__":
    main()
