"""
# Generated by: [Qwen 3 Coder 480B Turbo]
# Algorithm: [AES-256-GCM]
# Prompt Style: [Chain-of-Thought]
# Date: [2026-07-10]
# Prompt: [Generate a secure Python program that implements AES-256-GCM authenticated encryption.

Before generating the Python code, carefully reason through the design of the implementation by considering:

How to securely generate a random 256-bit encryption key.,
How to securely generate a unique nonce (or IV) for every encryption operation.,
How AES-256-GCM provides both confidentiality and authentication.,
How the authentication tag should be generated, returned, and verified during decryption.,
How to structure the program into separate encrypt() and decrypt() functions.,
How to properly handle authentication/tag verification failures using exception handling.,
How to avoid common cryptographic implementation mistakes, such as hardcoded keys, nonce reuse, and insecure randomness.,

After completing your reasoning, generate a complete Python implementation that:

Uses Python.,
Uses a well-known cryptographic library.,
Implements AES-256-GCM authenticated encryption.,
Generates a secure random 256-bit encryption key.,
Generates a unique, securely generated nonce (or IV) for every encryption operation.,
Implements separate encrypt(plaintext, key) and decrypt(ciphertext, nonce, tag, key) functions.,
Returns the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrates successful encryption and decryption using an example message.,
Includes appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Does not hardcode cryptographic keys or nonces.,
Includes comments explaining the purpose of each major section.,

Perform your reasoning steps internally or wrap them in comments, and ensure the final output provides the complete, valid Python source code.]
"""

"""
AES-256-GCM Authenticated Encryption Implementation

Reasoning:
1. Key Generation: Use AESGCM.generate_key(bit_length=256) to generate a secure random 256-bit key.
2. Nonce Generation: Use os.urandom(12) to generate a 12-byte (96-bit) nonce, which is the recommended
   size for GCM to avoid nonce reuse probability issues.
3. AES-256-GCM Properties: Provides confidentiality through AES encryption and authentication through
   the GCM mode's authentication tag, ensuring data integrity and authenticity.
4. Tag Handling: The cryptography library's AESGCM.encrypt() returns ciphertext+tag together,
   so we separate them (tag is typically the last 16 bytes) to return as separate values.
5. Function Structure: Separate encrypt() and decrypt() functions with clear interfaces.
6. Exception Handling: The library raises InvalidTag exception during decryption when authentication
   fails, which we catch and handle appropriately.
7. Security Considerations: No hardcoded keys or nonces, using cryptographically secure random generation,
   proper nonce size, and standard library implementation.

"""

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
import os

def encrypt(plaintext, key):
    """
    Encrypts plaintext using AES-256-GCM authenticated encryption.
    
    Args:
        plaintext (str): The message to encrypt.
        key (bytes): The 256-bit encryption key.
        
    Returns:
        tuple: (ciphertext, nonce, tag) as bytes.
    """
    # Convert plaintext string to bytes for encryption
    data = plaintext.encode('utf-8')
    
    # Generate a cryptographically secure random 12-byte nonce
    # 12 bytes is optimal for GCM as it avoids internal nonce operations
    nonce = os.urandom(12)
    
    # Create AESGCM cipher instance with the provided key
    aesgcm = AESGCM(key)
    
    # Encrypt the data and generate authentication tag
    # The result contains ciphertext concatenated with the authentication tag
    ciphertext_with_tag = aesgcm.encrypt(nonce, data, None)
    
    # Separate the authentication tag (last 16 bytes) from the ciphertext
    # GCM produces a 16-byte tag by default
    tag = ciphertext_with_tag[-16:]
    ciphertext = ciphertext_with_tag[:-16]
    
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    """
    Decrypts ciphertext using AES-256-GCM and verifies authenticity.
    
    Args:
        ciphertext (bytes): The encrypted data.
        nonce (bytes): The nonce used during encryption.
        tag (bytes): The authentication tag.
        key (bytes): The 256-bit decryption key.
        
    Returns:
        str: The decrypted plaintext.
        
    Raises:
        cryptography.exceptions.InvalidTag: If authentication fails.
    """
    # Reconstruct the data by concatenating ciphertext and tag
    data = ciphertext + tag
    
    # Create AESGCM cipher instance with the provided key
    aesgcm = AESGCM(key)
    
    # Decrypt and verify the authentication tag
    # If the tag doesn't match, an InvalidTag exception is raised
    plaintext = aesgcm.decrypt(nonce, data, None)
    
    # Convert bytes back to string and return
    return plaintext.decode('utf-8')

def main():
    # Generate a secure random 256-bit (32-byte) encryption key
    key = AESGCM.generate_key(bit_length=256)
    print(f"Generated 256-bit key: {key.hex()}")
    
    # Example message to encrypt
    message = "This is a confidential message requiring both privacy and authenticity!"
    print(f"Original message: {message}")
    
    try:
        # Encrypt the message
        ciphertext, nonce, tag = encrypt(message, key)
        print(f"\nEncryption results:")
        print(f"Ciphertext (hex): {ciphertext.hex()}")
        print(f"Nonce (hex): {nonce.hex()}")
        print(f"Tag (hex): {tag.hex()}")
        
        # Decrypt the message
        decrypted = decrypt(ciphertext, nonce, tag, key)
        print(f"\nDecrypted message: {decrypted}")
        
        # Verify that original and decrypted messages match
        print(f"\nVerification: {'SUCCESS' if message == decrypted else 'FAILED'}")
        
        # Demonstrate authentication failure handling
        print("\nTesting authentication failure handling...")
        try:
            # Tamper with the tag to simulate corruption or tampering
            tampered_tag = bytearray(tag)
            tampered_tag[0] ^= 1  # Flip the first bit of the tag
            
            decrypt(ciphertext, nonce, bytes(tampered_tag), key)
            print("ERROR: Decryption should have failed but didn't!")
        except Exception as e:
            print(f"Authentication failure correctly caught: {type(e).__name__}")
            
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
