"""
# Generated by: [Qwen 3 Coder 480B Turbo]
# Algorithm: [ChaCha20-Poly1305]
# Prompt Style: [Zero-shot]
# Date: [2026-07-10]
# Prompt: [Requirements:
Use Python.,
Use a well-known cryptographic library,
Implement a modern, secure authenticated encryption algorithm (AEAD), ChaCha20-Poly1305.,
Generate a random 256-bit encryption key.,
Generate a unique, securely generated nonce (or IV) appropriate for every encryption operation.,
Create separate encrypt() and decrypt() functions.,
Accept plaintext as a string.,
Return the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrate the encryption and decryption process using an example message.,
Include appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Include comments explaining the purpose of each major section.,

Return only the complete Python source code.]
"""

from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
import os

def encrypt(plaintext: str) -> tuple[bytes, bytes, bytes]:
    """
    Encrypts a plaintext string using ChaCha20-Poly1305.
    
    Args:
        plaintext: The string message to encrypt.
        
    Returns:
        A tuple containing:
        - ciphertext (bytes): The encrypted message.
        - nonce (bytes): The unique nonce used for encryption.
        - tag (bytes): The authentication tag.
    """
    # Generate a random 256-bit (32 bytes) encryption key
    key = ChaCha20Poly1305.generate_key()
    
    # Create a ChaCha20-Poly1305 cipher instance
    cipher = ChaCha20Poly1305(key)
    
    # Generate a unique 96-bit (12 bytes) nonce for each encryption operation
    nonce = os.urandom(12)
    
    # Encode the plaintext string to bytes
    plaintext_bytes = plaintext.encode('utf-8')
    
    # Encrypt the plaintext and generate the authentication tag
    # The ciphertext returned includes both the encrypted data and the tag
    ciphertext_with_tag = cipher.encrypt(nonce, plaintext_bytes, None)
    
    # In ChaCha20-Poly1305, the tag is appended to the ciphertext
    # We separate them for explicit return as requested
    tag = ciphertext_with_tag[-16:]  # Poly1305 tag is 16 bytes
    ciphertext = ciphertext_with_tag[:-16]
    
    return ciphertext, nonce, tag

def decrypt(ciphertext: bytes, nonce: bytes, tag: bytes, key: bytes) -> str:
    """
    Decrypts a ciphertext using ChaCha20-Poly1305.
    
    Args:
        ciphertext: The encrypted message.
        nonce: The nonce used during encryption.
        tag: The authentication tag.
        key: The encryption key.
        
    Returns:
        The decrypted plaintext string.
        
    Raises:
        cryptography.exceptions.InvalidTag: If authentication fails.
    """
    # Create a ChaCha20-Poly1305 cipher instance
    cipher = ChaCha20Poly1305(key)
    
    # Combine ciphertext and tag for decryption
    ciphertext_with_tag = ciphertext + tag
    
    try:
        # Decrypt and verify the authentication tag
        plaintext_bytes = cipher.decrypt(nonce, ciphertext_with_tag, None)
        
        # Decode bytes back to string
        plaintext = plaintext_bytes.decode('utf-8')
        return plaintext
    except Exception as e:
        # Re-raise any exception (typically InvalidTag) for handling by caller
        raise e

# Example usage
if __name__ == "__main__":
    # Example message to encrypt
    message = "This is a secret message."
    print(f"Original message: {message}")
    
    # Encrypt the message
    ciphertext, nonce, tag = encrypt(message)
    print(f"Ciphertext: {ciphertext.hex()}")
    print(f"Nonce: {nonce.hex()}")
    print(f"Tag: {tag.hex()}")
    
    # For decryption, we need to preserve the key
    # In a real application, the key would be stored securely
    key = ChaCha20Poly1305.generate_key()
    
    # Create a new encrypt function that returns the key for this example
    def encrypt_with_key(plaintext: str) -> tuple[bytes, bytes, bytes, bytes]:
        key = ChaCha20Poly1305.generate_key()
        cipher = ChaCha20Poly1305(key)
        nonce = os.urandom(12)
        plaintext_bytes = plaintext.encode('utf-8')
        ciphertext_with_tag = cipher.encrypt(nonce, plaintext_bytes, None)
        tag = ciphertext_with_tag[-16:]
        ciphertext = ciphertext_with_tag[:-16]
        return ciphertext, nonce, tag, key
    
    # Re-encrypt with key preservation for demonstration
    ciphertext, nonce, tag, key = encrypt_with_key(message)
    
    try:
        # Decrypt the message
        decrypted_message = decrypt(ciphertext, nonce, tag, key)
        print(f"Decrypted message: {decrypted_message}")
        
        # Demonstrate authentication failure with incorrect tag
        print("\nTesting authentication failure...")
        try:
            # Tamper with the tag
            wrong_tag = os.urandom(16)
            decrypt(ciphertext, nonce, wrong_tag, key)
        except Exception as e:
            print(f"Authentication failed as expected: {type(e).__name__}")
            
    except Exception as e:
        print(f"Decryption failed: {type(e).__name__}")
