"""
# Generated by: [Qwen 3 Coder 480B Turbo]
# Algorithm: [AES-256-GCM]
# Prompt Style: [Few-shot]
# Date: [2026-07-10]
# Prompt: [Generate a secure Python program that implements AES-256-GCM authenticated encryption.

Below is an example of the desired program structure. This example is only to illustrate the organization of the code and does not implement encryption.

Example:

import os

def encrypt(plaintext, key):
    # Generate a unique nonce (or IV)
    # Encrypt the plaintext to produce the ciphertext and authentication tag
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    # Verify the authentication tag and decrypt the ciphertext
    return plaintext

def main():
    message = "Hello, World!"

    # Generate a secure random 256-bit encryption key here
    key = ...

    ciphertext, nonce, tag = encrypt(message, key)
    decrypted = decrypt(ciphertext, nonce, tag, key)

    print("Original:", message)
    print("Recovered:", decrypted)

if name == "main":
    main()

Using the example above as a guide, generate a complete Python implementation that:

Uses a well-known cryptographic library.,
Generates a secure random 256-bit encryption key in the main workflow.,
Generates a unique, securely generated nonce (or IV) for every encryption operation.,
Implements separate encrypt(plaintext, key) and decrypt(ciphertext, nonce, tag, key) functions.,
Returns the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrates successful encryption and decryption using an example message.,
Includes appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Does not hardcode cryptographic keys or nonces.,
Includes comments explaining the purpose of each major section.,

Return only the complete Python source code]
"""

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
import os

def encrypt(plaintext, key):
    """
    Encrypts plaintext using AES-256-GCM.
    
    Args:
        plaintext (str): The plaintext message to encrypt.
        key (bytes): The 256-bit encryption key.
        
    Returns:
        tuple: (ciphertext, nonce, tag) as bytes.
    """
    # Convert plaintext to bytes
    data = plaintext.encode('utf-8')
    
    # Generate a unique 96-bit (12-byte) nonce for each encryption operation
    nonce = os.urandom(12)
    
    # Create AESGCM instance
    aesgcm = AESGCM(key)
    
    # Encrypt the data and authenticate
    # The result contains both the ciphertext and the authentication tag
    ciphertext_with_tag = aesgcm.encrypt(nonce, data, None)
    
    # Separate the tag from the ciphertext (last 16 bytes is the tag for GCM)
    tag = ciphertext_with_tag[-16:]
    ciphertext = ciphertext_with_tag[:-16]
    
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    """
    Decrypts ciphertext using AES-256-GCM and verifies authenticity.
    
    Args:
        ciphertext (bytes): The encrypted data.
        nonce (bytes): The nonce used during encryption.
        tag (bytes): The authentication tag.
        key (bytes): The 256-bit decryption key.
        
    Returns:
        str: The decrypted plaintext.
        
    Raises:
        cryptography.exceptions.InvalidTag: If authentication fails.
    """
    # Combine ciphertext and tag for decryption
    data = ciphertext + tag
    
    # Create AESGCM instance
    aesgcm = AESGCM(key)
    
    # Decrypt and verify authenticity
    plaintext = aesgcm.decrypt(nonce, data, None)
    
    # Convert bytes back to string
    return plaintext.decode('utf-8')

def main():
    # Generate a secure random 256-bit (32-byte) encryption key
    key = AESGCM.generate_key(bit_length=256)
    print(f"Generated 256-bit key: {key.hex()}")
    
    # Example message to encrypt
    message = "This is a secret message!"
    print(f"Original message: {message}")
    
    try:
        # Encrypt the message
        ciphertext, nonce, tag = encrypt(message, key)
        print(f"\nEncryption results:")
        print(f"Ciphertext: {ciphertext.hex()}")
        print(f"Nonce: {nonce.hex()}")
        print(f"Tag: {tag.hex()}")
        
        # Decrypt the message
        decrypted = decrypt(ciphertext, nonce, tag, key)
        print(f"\nDecrypted message: {decrypted}")
        
        # Verify that original and decrypted messages match
        print(f"\nVerification: {'SUCCESS' if message == decrypted else 'FAILED'}")
        
        # Demonstrate authentication failure handling
        print("\nTesting authentication failure handling...")
        try:
            # Tamper with the tag to simulate corruption
            tampered_tag = bytearray(tag)
            tampered_tag[0] ^= 1  # Flip a bit in the tag
            
            decrypt(ciphertext, nonce, bytes(tampered_tag), key)
            print("ERROR: Decryption should have failed but didn't!")
        except Exception as e:
            print(f"Authentication failure correctly caught: {type(e).__name__}")
            
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
