"""
# Generated by: [Qwen 3 Coder 480B Turbo]
# Algorithm: [ChaCha20-Poly1305]
# Prompt Style: [Few-shot]
# Date: [2026-07-10]
# Prompt: [Generate a secure Python program that implements ChaCha20-Poly1305 authenticated encryption.

Below is an example of the desired program structure. This example is only to illustrate the organization of the code and does not implement encryption.

Example:

import os

def encrypt(plaintext, key):
    # Generate a unique nonce
    # Encrypt the plaintext to produce the ciphertext and Poly1305 authentication tag
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    # Verify the Poly1305 authentication tag and decrypt the ciphertext
    return plaintext

def main():
    message = "Hello, World!"

    # Generate a secure random 256-bit encryption key here
    key = ...

    ciphertext, nonce, tag = encrypt(message, key)
    decrypted = decrypt(ciphertext, nonce, tag, key)

    print("Original:", message)
    print("Recovered:", decrypted)

if name == "main":
    main()

Using the example above as a guide, generate a complete Python implementation that:

Uses a well-known cryptographic library.,
Generates a secure random 256-bit encryption key in the main workflow.,
Generates a unique, securely generated nonce appropriate for ChaCha20-Poly1305 for every encryption operation.,
Implements separate encrypt(plaintext, key) and decrypt(ciphertext, nonce, tag, key) functions.,
Returns the ciphertext, nonce, and authentication tag as separate values from the encrypt() function.,
Demonstrates successful encryption and decryption using an example message.,
Includes appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Does not hardcode cryptographic keys or nonces.,
Includes comments explaining the purpose of each major section.,

Return only the complete Python source code.]
"""

from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
import os

def encrypt(plaintext, key):
    """
    Encrypts plaintext using ChaCha20-Poly1305 authenticated encryption.
    
    Args:
        plaintext (str): The message to encrypt.
        key (bytes): The 256-bit encryption key.
        
    Returns:
        tuple: (ciphertext, nonce, tag) as bytes.
    """
    # Create a ChaCha20-Poly1305 cipher instance with the provided key
    cipher = ChaCha20Poly1305(key)
    
    # Generate a unique 96-bit (12 bytes) nonce for this encryption operation
    # This nonce must never be reused with the same key
    nonce = os.urandom(12)
    
    # Encode the plaintext string to bytes for encryption
    plaintext_bytes = plaintext.encode('utf-8')
    
    # Encrypt the plaintext and generate authentication tag
    # The ciphertext returned includes both encrypted data and the authentication tag
    ciphertext_with_tag = cipher.encrypt(nonce, plaintext_bytes, None)
    
    # Separate the ciphertext and authentication tag
    # ChaCha20-Poly1305 uses a 128-bit (16 bytes) Poly1305 authentication tag
    tag = ciphertext_with_tag[-16:]
    ciphertext = ciphertext_with_tag[:-16]
    
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    """
    Decrypts ciphertext using ChaCha20-Poly1305 authenticated decryption.
    
    Args:
        ciphertext (bytes): The encrypted message.
        nonce (bytes): The nonce used during encryption.
        tag (bytes): The authentication tag.
        key (bytes): The 256-bit encryption key.
        
    Returns:
        str: The decrypted plaintext message.
        
    Raises:
        cryptography.exceptions.InvalidTag: If authentication fails.
    """
    # Create a ChaCha20-Poly1305 cipher instance with the provided key
    cipher = ChaCha20Poly1305(key)
    
    # Combine ciphertext and tag for decryption
    ciphertext_with_tag = ciphertext + tag
    
    # Decrypt and verify the authentication tag
    # This will raise an InvalidTag exception if verification fails
    plaintext_bytes = cipher.decrypt(nonce, ciphertext_with_tag, None)
    
    # Decode bytes back to string
    plaintext = plaintext_bytes.decode('utf-8')
    return plaintext

def main():
    # Example message to encrypt
    message = "Hello, World!"
    
    # Generate a secure random 256-bit (32 bytes) encryption key
    key = ChaCha20Poly1305.generate_key()
    
    # Encrypt the message
    ciphertext, nonce, tag = encrypt(message, key)
    
    # Decrypt the message
    try:
        decrypted = decrypt(ciphertext, nonce, tag, key)
        print("Original:", message)
        print("Recovered:", decrypted)
        
        # Demonstrate authentication failure handling
        print("\nTesting authentication failure...")
        try:
            # Try to decrypt with an incorrect tag
            wrong_tag = os.urandom(16)
            decrypt(ciphertext, nonce, wrong_tag, key)
        except Exception as e:
            print(f"Authentication failed as expected: {type(e).__name__}")
            
    except Exception as e:
        print(f"Decryption failed: {type(e).__name__}")

if __name__ == "__main__":
    main()
