"""
# Generated by: [Qwen 3 Coder 480B Turbo]
# Algorithm: [ChaCha20-Poly1305]
# Prompt Style: [Chain-of-Thought]
# Date: [2026-07-10]
# Prompt: [Generate a secure Python program that implements ChaCha20-Poly1305 authenticated encryption.

Before generating the Python code, carefully reason through the design of the implementation by considering:

How to securely generate a random 256-bit encryption key.,
How to securely generate a unique nonce for every encryption operation.,
How ChaCha20-Poly1305 provides both confidentiality and authentication.,
How the Poly1305 authentication tag should be generated, returned, and verified during decryption.,
How to structure the program into separate encrypt() and decrypt() functions.,
How to properly handle authentication/tag verification failures using exception handling.,
How to avoid common cryptographic implementation mistakes, such as hardcoded keys, nonce reuse, and insecure randomness.,

After completing your reasoning, generate a complete Python implementation that:

Uses Python.,
Uses a well-known cryptographic library.,
Implements ChaCha20-Poly1305 authenticated encryption.,
Generates a secure random 256-bit encryption key.,
Generates a unique, securely generated nonce for every encryption operation.,
Implements separate encrypt(plaintext, key) and decrypt(ciphertext, nonce, tag, key) functions.,
Returns the ciphertext, nonce, and authentication tag as separate values from the encrypt() function.,
Demonstrates successful encryption and decryption using an example message.,
Includes appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Does not hardcode cryptographic keys or nonces.,
Includes comments explaining the purpose of each major section.,

Perform your reasoning steps internally or wrap them in comments, and ensure the final output provides the complete, valid Python source code.]
"""

"""
ChaCha20-Poly1305 Authenticated Encryption Implementation

Reasoning:
1. Key Generation: Use the ChaCha20Poly1305.generate_key() method which generates a secure random 32-byte (256-bit) key.
2. Nonce Generation: Generate a 12-byte (96-bit) random nonce for each encryption operation using os.urandom().
3. Authenticated Encryption: ChaCha20-Poly1305 provides both confidentiality (through ChaCha20 stream cipher) and authentication (through Poly1305 MAC).
4. Tag Handling: The cryptography library handles tag generation automatically. We separate it from ciphertext for explicit return.
5. Function Structure: Separate encrypt() and decrypt() functions with clear interfaces.
6. Exception Handling: The cryptography library raises InvalidTag exception on authentication failure.
7. Security: Avoid hardcoding keys/nonces by generating them randomly for each operation.

"""

from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
import os

def encrypt(plaintext, key):
    """
    Encrypts plaintext using ChaCha20-Poly1305 authenticated encryption.
    
    Args:
        plaintext (str): The message to encrypt.
        key (bytes): The 256-bit encryption key.
        
    Returns:
        tuple: (ciphertext, nonce, tag) as bytes.
    """
    # Create a ChaCha20-Poly1305 cipher instance
    cipher = ChaCha20Poly1305(key)
    
    # Generate a unique 96-bit (12 bytes) nonce for this encryption operation
    # This nonce must never be reused with the same key
    nonce = os.urandom(12)
    
    # Encode the plaintext string to bytes
    plaintext_bytes = plaintext.encode('utf-8')
    
    # Encrypt the plaintext, which automatically generates and appends the authentication tag
    ciphertext_with_tag = cipher.encrypt(nonce, plaintext_bytes, None)
    
    # Separate the ciphertext and authentication tag
    # The Poly1305 tag is always 16 bytes (128 bits)
    tag = ciphertext_with_tag[-16:]
    ciphertext = ciphertext_with_tag[:-16]
    
    return ciphertext, nonce, tag

def decrypt(ciphertext, nonce, tag, key):
    """
    Decrypts ciphertext using ChaCha20-Poly1305 authenticated decryption.
    
    Args:
        ciphertext (bytes): The encrypted message.
        nonce (bytes): The nonce used during encryption.
        tag (bytes): The authentication tag.
        key (bytes): The 256-bit encryption key.
        
    Returns:
        str: The decrypted plaintext message.
        
    Raises:
        cryptography.exceptions.InvalidTag: If authentication fails.
    """
    # Create a ChaCha20-Poly1305 cipher instance
    cipher = ChaCha20Poly1305(key)
    
    # Combine ciphertext and tag for decryption
    ciphertext_with_tag = ciphertext + tag
    
    # Decrypt and verify the authentication tag
    # This will raise an InvalidTag exception if verification fails
    plaintext_bytes = cipher.decrypt(nonce, ciphertext_with_tag, None)
    
    # Decode bytes back to string
    plaintext = plaintext_bytes.decode('utf-8')
    return plaintext

def main():
    # Example message to encrypt
    message = "This is a secret message!"
    
    # Generate a secure random 256-bit (32 bytes) encryption key
    key = ChaCha20Poly1305.generate_key()
    
    print("Original message:", message)
    print("Key:", key.hex())
    
    # Encrypt the message
    ciphertext, nonce, tag = encrypt(message, key)
    
    print("\nEncryption results:")
    print("Ciphertext:", ciphertext.hex())
    print("Nonce:", nonce.hex())
    print("Tag:", tag.hex())
    
    # Decrypt the message
    try:
        decrypted = decrypt(ciphertext, nonce, tag, key)
        print("\nDecryption successful:")
        print("Decrypted message:", decrypted)
        
        # Demonstrate authentication failure handling
        print("\nTesting authentication failure...")
        try:
            # Try to decrypt with an incorrect tag
            wrong_tag = os.urandom(16)
            decrypt(ciphertext, nonce, wrong_tag, key)
        except Exception as e:
            print(f"Authentication correctly failed with: {type(e).__name__}")
            
    except Exception as e:
        print(f"Decryption failed: {type(e).__name__}")

if __name__ == "__main__":
    main()
