"""
# Generated by: [Qwen 3 Coder 480B Turbo]
# Algorithm: [AES-256-GCM]
# Prompt Style: [Zero-shot]
# Date: [2026-07-10]
# Prompt: [Requirements:
Use Python.,
Use a well-known cryptographic library,
Implement a modern, secure authenticated encryption algorithm (AEAD), AES-GCM.,
Generate a random 256-bit encryption key.,
Generate a unique, securely generated nonce (or IV) appropriate for every encryption operation.,
Create separate encrypt() and decrypt() functions.,
Accept plaintext as a string.,
Return the ciphertext, nonce (or IV), and authentication tag as separate values from the encrypt() function.,
Demonstrate the encryption and decryption process using an example message.,
Include appropriate exception handling, specifically catching authentication/tag verification failures during decryption.,
Include comments explaining the purpose of each major section.,

Return only the complete Python source code.]
"""

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
import os
import base64

def generate_key():
    """Generate a random 256-bit encryption key."""
    return AESGCM.generate_key(bit_length=256)

def encrypt(plaintext: str, key: bytes) -> tuple:
    """
    Encrypt a plaintext string using AES-GCM.
    
    Args:
        plaintext: The string to encrypt
        key: The encryption key (must be 256 bits)
        
    Returns:
        tuple: (ciphertext, nonce, tag) as bytes
    """
    # Convert plaintext string to bytes
    data = plaintext.encode('utf-8')
    
    # Generate a random nonce (12 bytes is standard for GCM)
    nonce = os.urandom(12)
    
    # Create AESGCM instance
    aesgcm = AESGCM(key)
    
    # Encrypt the data and get the ciphertext with tag
    ciphertext_with_tag = aesgcm.encrypt(nonce, data, None)
    
    # In AESGCM, the tag is appended to the ciphertext
    # We'll separate them for the required interface
    # Tag is typically 16 bytes
    tag = ciphertext_with_tag[-16:]
    ciphertext = ciphertext_with_tag[:-16]
    
    return (ciphertext, nonce, tag)

def decrypt(ciphertext: bytes, nonce: bytes, tag: bytes, key: bytes) -> str:
    """
    Decrypt a ciphertext using AES-GCM.
    
    Args:
        ciphertext: The encrypted data
        nonce: The nonce used during encryption
        tag: The authentication tag
        key: The encryption key
        
    Returns:
        str: The decrypted plaintext
        
    Raises:
        cryptography.exceptions.InvalidTag: If authentication fails
    """
    # Combine ciphertext and tag for decryption
    data = ciphertext + tag
    
    # Create AESGCM instance
    aesgcm = AESGCM(key)
    
    try:
        # Decrypt and verify authenticity
        plaintext = aesgcm.decrypt(nonce, data, None)
        return plaintext.decode('utf-8')
    except Exception as e:
        # Re-raise with a clearer message
        raise Exception("Decryption failed: Authentication tag mismatch or corrupted data") from e

# Example usage
if __name__ == "__main__":
    # Generate a key
    key = generate_key()
    print(f"Generated key: {base64.b64encode(key).decode()}")
    
    # Example message
    message = "This is a secret message that needs encryption!"
    print(f"Original message: {message}")
    
    try:
        # Encrypt the message
        ciphertext, nonce, tag = encrypt(message, key)
        print(f"Ciphertext: {base64.b64encode(ciphertext).decode()}")
        print(f"Nonce: {base64.b64encode(nonce).decode()}")
        print(f"Tag: {base64.b64encode(tag).decode()}")
        
        # Decrypt the message
        decrypted = decrypt(ciphertext, nonce, tag, key)
        print(f"Decrypted message: {decrypted}")
        
        # Demonstrate authentication failure
        print("\nTesting authentication failure...")
        try:
            # Tamper with the tag
            wrong_tag = tag[:-1] + bytes([tag[-1] ^ 1])
            decrypt(ciphertext, nonce, wrong_tag, key)
        except Exception as e:
            print(f"Authentication error caught: {e}")
            
    except Exception as e:
        print(f"Error: {e}")
